print("Iulian Caraman")
print("15.01.2005")
print("Balti")
print("Nationalitatea:Moldovan")
print("Nascut in Balti")
print("necasatorit")
print("nr de telefon:061136800")
print("adresa:Voluntarilor 20")
print("hobby:fotbalul")
print("invat:I.P.L.T,,Mihai Eminescu,,")